// Code generated by "asynq-codegen"; DO NOT EDIT

package {{ .PackageName }}

import (
    "context"
    "encoding/json"
    "fmt"
    "io"
    "time"

    "github.com/hibiken/asynq"
)

// Auto-generated constants for use with [asynq.NewTask], [asynq.ServeMux.Handle],
// and [asynq.ServeMux.HandleFunc].
const (
{{- range $arg := .Comments }}
    // Type{{ .StructName }} is wired to [asynq.Task.Type], [asynq.ServeMux.Handle] and [asynq.ServeMux.HandleFunc].
    Type{{ .StructName }} = "{{ .TypeName }}"
{{- end -}}
)

{{/* Interfaces of asynq package */}}
type asynqClient interface {
    // Enqueue is https://pkg.go.dev/github.com/hibiken/asynq#Client.Enqueue.
    Enqueue(*asynq.Task, ...asynq.Option) (*asynq.TaskInfo, error)
    // EnqueueContext is https://pkg.go.dev/github.com/hibiken/asynq#Client.EnqueueContext.
    EnqueueContext(context.Context, *asynq.Task, ...asynq.Option) (*asynq.TaskInfo, error)
}

type asynqMux interface {
    // HandleFunc is https://pkg.go.dev/github.com/hibiken/asynq#ServeMux.HandleFunc.
    HandleFunc(string, func(context.Context, *asynq.Task) error)
}

{{/* Aliases for consumer functions */}}
{{- range $arg := .Comments }}
// {{ .StructName }}Processor describes a function that processes [{{ .StructName }}].
//
// This type is auto-generated.
type {{ .StructName }}Processor = func (context.Context, *{{ .StructName }}, map[string]string) error
{{ end -}}

// Processors defines methods to process messages by their type.
//
// This type is auto-generated.
type Processors struct {
{{- range $arg := .Comments }}
    {{ .StructName }} {{ .StructName }}Processor
{{- end -}}
}

// Handle register all non-nil handlers with [asynq.ServeMux.HandleFunc].
//
// This function is auto-generated.
func (p *Processors) Handle(mux asynqMux) {
    {{- range $arg := .Comments }}
        if p.{{ .StructName }} != nil {
            mux.HandleFunc(Type{{ .StructName }}, New{{ .StructName }}Processor(p.{{ .StructName }}))
        }
    {{ end -}}
}

// HandleAll register all handlers with [asynq.ServeMux.HandleFunc]. It returns an error if any handler is nil.
//
// This function is auto-generated.
func (p *Processors) HandleAll(mux asynqMux) error {
    {{- range $arg := .Comments }}
        if p.{{ .StructName }} == nil {
            return fmt.Errorf("nil Processors.{{ .StructName }}")
        }
    {{ end }}

    {{- range $arg := .Comments }}
        mux.HandleFunc(Type{{ .StructName }}, New{{ .StructName }}Processor(p.{{ .StructName }}))
    {{ end }}

    return nil
}

// Run wires up a new [asynq.Server] with an [asynq.ServeMux] instantiated using the provided
// options and middlewares.
//
// This function is auto-generated.
func (p *Processors) Run(redisConnOpt asynq.RedisConnOpt, cfg asynq.Config, middlewares ...asynq.MiddlewareFunc) error {
    mux := asynq.NewServeMux()
    mux.Use(middlewares...)

    if err := p.HandleAll(mux); err != nil {
        return fmt.Errorf("registering mux handler: %w", err)
    }

    return asynq.NewServer(redisConnOpt, cfg).Run(mux)
}

{{/* Tasks factories */}}
{{- range $arg := .Comments }}
// New{{ .StructName }}FromJSON consumes a JSON input and returns a [{{ .StructName }}].
// Any error returned by [json.Unmarshal] will be returned as-is.
//
// This function is auto-generated.
func New{{ .StructName }}FromJSON(r io.Reader) (*{{ .StructName }}, error) {
    var out {{ .StructName }}

    if err :=  json.NewDecoder(r).Decode(&out); err != nil {
        return nil, err
    }

    return &out, nil
}

// New{{ .StructName }}FromJSONBytes reads a JSON bytestream and returns a [{{ .StructName }}].
//
// Any error returned by [json.Unmarshal] will be returned as-is.
//
// This function is auto-generated.
func New{{ .StructName }}FromJSONBytes(b []byte) (*{{ .StructName }}, error) {
    var out {{ .StructName }}

    if err := json.Unmarshal(b, &out); err != nil {
        return nil, err
    }

    return &out, nil
}

// New{{ .StructName }}Task calls [New{{ .StructName }}TaskWithHeaders] with nil headers.
//
// This function is auto-generated.
func New{{ .StructName }}Task(t *{{ .StructName }}) (*asynq.Task, error) {
    return New{{ .StructName }}TaskWithHeaders(t, nil)
}

// New{{ .StructName }}TaskWithHeaders takes a [{{ .StructName }}] pointer and returns a new [asynq.Task] with
// its typename set to [Type{{ .StructName }}].
//
// It calls [asynq.NewTaskWithHeaders] introduced with asynq 0.26.0.
//
// It returns an error if the pointer is nil, or if it cannot be marshalled.
//
// Task's options:
//
//    - Max retries: {{ .Retry }}
//    - Retention: {{ .Retention.String }}
//    - Timeout: {{ .Timeout.String }}
//
// This function is auto-generated.
func New{{ .StructName }}TaskWithHeaders(t *{{ .StructName }}, headers map[string]string) (*asynq.Task, error) {
    if t == nil {
        return nil, fmt.Errorf("nil {{ .StructName }} pointer")
    }

    payload, err := json.Marshal(t)
    if err != nil {
        return nil, fmt.Errorf("marshalling {{ .StructName }}: %w", err)
    }

    return asynq.NewTaskWithHeaders(
        Type{{ .StructName }},
        payload,
        headers,
        asynq.MaxRetry({{ .Retry }}),
        asynq.Retention({{ .Retention.Milliseconds }} * time.Millisecond),
        asynq.Timeout({{ .Timeout.Milliseconds }} * time.Millisecond),
    ), nil
}
{{ end -}}

{{/* Consumer factories */}}
{{- range $arg := .Comments }}
    // New{{ .StructName }}Processor wraps a [{{ .StructName }}Processor] function so that it can be passed
    // to [asynq.ServeMux.Handle] and [asynq.ServeMux.HandleFunc].
    //
    // Notes about the returned function:
    //     - it will reject nil tasks and tasks of which the typename does not match [Type{{ .StructName }}].
    //     - it will return an error if a task's payload cannot be unmarshalled.
    //     - it will return any received error as-is, including [asynq.SkipRetry] and [asynq.RevokeTask].
    //
    // This function is auto-generated.
    func New{{ .StructName }}Processor(fn {{ .StructName }}Processor) func(context.Context, *asynq.Task) error {
        return func (ctx context.Context, task *asynq.Task) error {
            if task == nil {
                return fmt.Errorf("{{ .StructName }}Processor invoked with nil task")
            }

            if task.Type() != Type{{ .StructName }} {
                return fmt.Errorf("{{ .StructName }}Processor invoked with task of type %s instead of %s", task.Type(), Type{{ .StructName }})
            }

            p := task.Payload()

            if len(p) == 0 {
                return fmt.Errorf("{{ .StructName }}Processor invoked with void payload")
            }

            var message {{ .StructName }}

            if err := json.Unmarshal(p, &message); err != nil {
                return fmt.Errorf("{{ .StructName }}Processor invoked with corrupt payload: %w", err)
            }

            h := task.Headers()
            if h == nil {
                h = map[string]string{}
            }

            return fn(ctx, &message, h)
        }
    }
{{ end -}}

{{/* Functions to enqueue tasks. */}}
{{- range $arg := .Comments }}
    // Enqueue{{ .StructName }} pushes a [{{ .StructName }}] task to the queue.
    //
    // Additional [asynq.Option] can be passed to override the options set by [New{{ .StructName }}Task].
    //
    // This function is auto-generated.
    func Enqueue{{ .StructName }}(client asynqClient, message *{{ .StructName }}, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
        task, err := New{{ .StructName }}TaskWithHeaders(message, nil)
        if err != nil {
            return nil, nil, err
        }

        info, err := client.Enqueue(task, opts...)
        if err != nil {
            return nil, nil, err
        }

        return task, info, nil
    }

    // Enqueue{{ .StructName }}Context pushes a [{{ .StructName }}] task to the queue.
    //
    // Additional [asynq.Option] can be passed to override the options set by [New{{ .StructName }}Task].
    //
    // This function is auto-generated.
    func Enqueue{{ .StructName }}Context(ctx context.Context, client asynqClient, message *{{ .StructName }}, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
        return Enqueue{{ .StructName }}ContextWithHeaders(ctx, client, message, nil, opts...)
    }

    // Enqueue{{ .StructName }}ContextWithHeaders pushes a [{{ .StructName }}] task to the queue.
    //
    // It supports task headers introduced with asynq 0.26.0.
    //
    // Additional [asynq.Option] can be passed to override the options set by [New{{ .StructName }}Task].
    //
    // This function is auto-generated.
    func Enqueue{{ .StructName }}ContextWithHeaders(ctx context.Context, client asynqClient, message *{{ .StructName }}, headers map[string]string, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
        task, err := New{{ .StructName }}TaskWithHeaders(message, headers)
        if err != nil {
            return nil, nil, err
        }

        info, err := client.EnqueueContext(ctx, task, opts...)
        if err != nil {
            return nil, nil, err
        }

        return task, info, nil
    }

    // Enqueue{{ .StructName }}WithHeaders pushes a [{{ .StructName }}] task to the queue.
    //
    // It supports task headers introduced with asynq 0.26.0.
    //
    // Additional [asynq.Option] can be passed to override the options set by [New{{ .StructName }}Task].
    //
    // This function is auto-generated.
    func Enqueue{{ .StructName }}WithHeaders(client asynqClient, message *{{ .StructName }}, headers map[string]string, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
        task, err := New{{ .StructName }}TaskWithHeaders(message, headers)
        if err != nil {
            return nil, nil, err
        }

        info, err := client.Enqueue(task, opts...)
        if err != nil {
            return nil, nil, err
        }

        return task, info, nil
    }
{{ end -}}