// Package asynqcodegen provides a small tool to auto-generate asynq tasks and consumers.
//
// It only helps to generate the boilerplate code using the same conventions shown in [asynq quickstart].
//
// [asynq quickstart]: https://github.com/hibiken/asynq#quickstart
package asynqcodegen

import (
	"log/slog"
	"os"
	"path/filepath"
)

// GeneratedFileName is the default name of any file generated by this tool.
const GeneratedFileName = "asynq_generated.go"

// Main is the command's entrypoint. It calls [Inspect] and [Generate] in the current working directory.
func Main(cwd string) error {
	dst := filepath.Join(cwd, GeneratedFileName)

	os.Remove(dst)

	inspectResult, err := Inspect(cwd)
	if err != nil {
		return err
	}

	if err := Generate(inspectResult, dst); err != nil {
		return err
	}

	slog.Info("asynq-codegen generated",
		slog.Int("structs", len(inspectResult.Comments)),
		slog.String("file", dst),
		slog.String("package", inspectResult.PackageName),
	)

	return nil
}
