// Code generated by "asynq-codegen"; DO NOT EDIT

package example01

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"time"

	"github.com/hibiken/asynq"
)

// Auto-generated constants for use with [asynq.NewTask], [asynq.ServeMux.Handle],
// and [asynq.ServeMux.HandleFunc].
const (
	// TypeSendEmail is wired to [asynq.Task.Type], [asynq.ServeMux.Handle] and [asynq.ServeMux.HandleFunc].
	TypeSendEmail = "example01:send_email"
	// TypeSendSMS is wired to [asynq.Task.Type], [asynq.ServeMux.Handle] and [asynq.ServeMux.HandleFunc].
	TypeSendSMS = "example01:send_sms_message"
)

type asynqClient interface {
	// Enqueue is https://pkg.go.dev/github.com/hibiken/asynq#Client.Enqueue.
	Enqueue(*asynq.Task, ...asynq.Option) (*asynq.TaskInfo, error)
	// EnqueueContext is https://pkg.go.dev/github.com/hibiken/asynq#Client.EnqueueContext.
	EnqueueContext(context.Context, *asynq.Task, ...asynq.Option) (*asynq.TaskInfo, error)
}

type asynqMux interface {
	// HandleFunc is https://pkg.go.dev/github.com/hibiken/asynq#ServeMux.HandleFunc.
	HandleFunc(string, func(context.Context, *asynq.Task) error)
}

// SendEmailProcessor describes a function that processes [SendEmail].
//
// This type is auto-generated.
type SendEmailProcessor = func(context.Context, *SendEmail, map[string]string) error

// SendSMSProcessor describes a function that processes [SendSMS].
//
// This type is auto-generated.
type SendSMSProcessor = func(context.Context, *SendSMS, map[string]string) error

// Processors defines methods to process messages by their type.
//
// This type is auto-generated.
type Processors struct {
	SendEmail SendEmailProcessor
	SendSMS   SendSMSProcessor
}

// Handle register all non-nil handlers with [asynq.ServeMux.HandleFunc].
//
// This function is auto-generated.
func (p *Processors) Handle(mux asynqMux) {
	if p.SendEmail != nil {
		mux.HandleFunc(TypeSendEmail, NewSendEmailProcessor(p.SendEmail))
	}

	if p.SendSMS != nil {
		mux.HandleFunc(TypeSendSMS, NewSendSMSProcessor(p.SendSMS))
	}
}

// HandleAll register all handlers with [asynq.ServeMux.HandleFunc]. It returns an error if any handler is nil.
//
// This function is auto-generated.
func (p *Processors) HandleAll(mux asynqMux) error {
	if p.SendEmail == nil {
		return fmt.Errorf("nil Processors.SendEmail")
	}

	if p.SendSMS == nil {
		return fmt.Errorf("nil Processors.SendSMS")
	}

	mux.HandleFunc(TypeSendEmail, NewSendEmailProcessor(p.SendEmail))

	mux.HandleFunc(TypeSendSMS, NewSendSMSProcessor(p.SendSMS))

	return nil
}

// Run wires up a new [asynq.Server] with an [asynq.ServeMux] instantiated using the provided
// options and middlewares.
//
// This function is auto-generated.
func (p *Processors) Run(redisConnOpt asynq.RedisConnOpt, cfg asynq.Config, middlewares ...asynq.MiddlewareFunc) error {
	mux := asynq.NewServeMux()
	mux.Use(middlewares...)

	if err := p.HandleAll(mux); err != nil {
		return fmt.Errorf("registering mux handler: %w", err)
	}

	return asynq.NewServer(redisConnOpt, cfg).Run(mux)
}

// NewSendEmailFromJSON consumes a JSON input and returns a [SendEmail].
// Any error returned by [json.Unmarshal] will be returned as-is.
//
// This function is auto-generated.
func NewSendEmailFromJSON(r io.Reader) (*SendEmail, error) {
	var out SendEmail

	if err := json.NewDecoder(r).Decode(&out); err != nil {
		return nil, err
	}

	return &out, nil
}

// NewSendEmailFromJSONBytes reads a JSON bytestream and returns a [SendEmail].
//
// Any error returned by [json.Unmarshal] will be returned as-is.
//
// This function is auto-generated.
func NewSendEmailFromJSONBytes(b []byte) (*SendEmail, error) {
	var out SendEmail

	if err := json.Unmarshal(b, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// NewSendEmailTask calls [NewSendEmailTaskWithHeaders] with nil headers.
//
// This function is auto-generated.
func NewSendEmailTask(t *SendEmail) (*asynq.Task, error) {
	return NewSendEmailTaskWithHeaders(t, nil)
}

// NewSendEmailTaskWithHeaders takes a [SendEmail] pointer and returns a new [asynq.Task] with
// its typename set to [TypeSendEmail].
//
// It calls [asynq.NewTaskWithHeaders] introduced with asynq 0.26.0.
//
// It returns an error if the pointer is nil, or if it cannot be marshalled.
//
// Task's options:
//
//   - Max retries: 5
//   - Retention: 24h0m0s
//   - Timeout: 1m0s
//
// This function is auto-generated.
func NewSendEmailTaskWithHeaders(t *SendEmail, headers map[string]string) (*asynq.Task, error) {
	if t == nil {
		return nil, fmt.Errorf("nil SendEmail pointer")
	}

	payload, err := json.Marshal(t)
	if err != nil {
		return nil, fmt.Errorf("marshalling SendEmail: %w", err)
	}

	return asynq.NewTaskWithHeaders(
		TypeSendEmail,
		payload,
		headers,
		asynq.MaxRetry(5),
		asynq.Retention(86400000*time.Millisecond),
		asynq.Timeout(60000*time.Millisecond),
	), nil
}

// NewSendSMSFromJSON consumes a JSON input and returns a [SendSMS].
// Any error returned by [json.Unmarshal] will be returned as-is.
//
// This function is auto-generated.
func NewSendSMSFromJSON(r io.Reader) (*SendSMS, error) {
	var out SendSMS

	if err := json.NewDecoder(r).Decode(&out); err != nil {
		return nil, err
	}

	return &out, nil
}

// NewSendSMSFromJSONBytes reads a JSON bytestream and returns a [SendSMS].
//
// Any error returned by [json.Unmarshal] will be returned as-is.
//
// This function is auto-generated.
func NewSendSMSFromJSONBytes(b []byte) (*SendSMS, error) {
	var out SendSMS

	if err := json.Unmarshal(b, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// NewSendSMSTask calls [NewSendSMSTaskWithHeaders] with nil headers.
//
// This function is auto-generated.
func NewSendSMSTask(t *SendSMS) (*asynq.Task, error) {
	return NewSendSMSTaskWithHeaders(t, nil)
}

// NewSendSMSTaskWithHeaders takes a [SendSMS] pointer and returns a new [asynq.Task] with
// its typename set to [TypeSendSMS].
//
// It calls [asynq.NewTaskWithHeaders] introduced with asynq 0.26.0.
//
// It returns an error if the pointer is nil, or if it cannot be marshalled.
//
// Task's options:
//
//   - Max retries: 5
//   - Retention: 24h0m0s
//   - Timeout: 1m0s
//
// This function is auto-generated.
func NewSendSMSTaskWithHeaders(t *SendSMS, headers map[string]string) (*asynq.Task, error) {
	if t == nil {
		return nil, fmt.Errorf("nil SendSMS pointer")
	}

	payload, err := json.Marshal(t)
	if err != nil {
		return nil, fmt.Errorf("marshalling SendSMS: %w", err)
	}

	return asynq.NewTaskWithHeaders(
		TypeSendSMS,
		payload,
		headers,
		asynq.MaxRetry(5),
		asynq.Retention(86400000*time.Millisecond),
		asynq.Timeout(60000*time.Millisecond),
	), nil
}

// NewSendEmailProcessor wraps a [SendEmailProcessor] function so that it can be passed
// to [asynq.ServeMux.Handle] and [asynq.ServeMux.HandleFunc].
//
// Notes about the returned function:
//     - it will reject nil tasks and tasks of which the typename does not match [TypeSendEmail].
//     - it will return an error if a task's payload cannot be unmarshalled.
//     - it will return any received error as-is, including [asynq.SkipRetry] and [asynq.RevokeTask].
//
// This function is auto-generated.
func NewSendEmailProcessor(fn SendEmailProcessor) func(context.Context, *asynq.Task) error {
	return func(ctx context.Context, task *asynq.Task) error {
		if task == nil {
			return fmt.Errorf("SendEmailProcessor invoked with nil task")
		}

		if task.Type() != TypeSendEmail {
			return fmt.Errorf("SendEmailProcessor invoked with task of type %s instead of %s", task.Type(), TypeSendEmail)
		}

		p := task.Payload()

		if len(p) == 0 {
			return fmt.Errorf("SendEmailProcessor invoked with void payload")
		}

		var message SendEmail

		if err := json.Unmarshal(p, &message); err != nil {
			return fmt.Errorf("SendEmailProcessor invoked with corrupt payload: %w", err)
		}

		h := task.Headers()
		if h == nil {
			h = map[string]string{}
		}

		return fn(ctx, &message, h)
	}
}

// NewSendSMSProcessor wraps a [SendSMSProcessor] function so that it can be passed
// to [asynq.ServeMux.Handle] and [asynq.ServeMux.HandleFunc].
//
// Notes about the returned function:
//     - it will reject nil tasks and tasks of which the typename does not match [TypeSendSMS].
//     - it will return an error if a task's payload cannot be unmarshalled.
//     - it will return any received error as-is, including [asynq.SkipRetry] and [asynq.RevokeTask].
//
// This function is auto-generated.
func NewSendSMSProcessor(fn SendSMSProcessor) func(context.Context, *asynq.Task) error {
	return func(ctx context.Context, task *asynq.Task) error {
		if task == nil {
			return fmt.Errorf("SendSMSProcessor invoked with nil task")
		}

		if task.Type() != TypeSendSMS {
			return fmt.Errorf("SendSMSProcessor invoked with task of type %s instead of %s", task.Type(), TypeSendSMS)
		}

		p := task.Payload()

		if len(p) == 0 {
			return fmt.Errorf("SendSMSProcessor invoked with void payload")
		}

		var message SendSMS

		if err := json.Unmarshal(p, &message); err != nil {
			return fmt.Errorf("SendSMSProcessor invoked with corrupt payload: %w", err)
		}

		h := task.Headers()
		if h == nil {
			h = map[string]string{}
		}

		return fn(ctx, &message, h)
	}
}

// EnqueueSendEmail pushes a [SendEmail] task to the queue.
//
// Additional [asynq.Option] can be passed to override the options set by [NewSendEmailTask].
//
// This function is auto-generated.
func EnqueueSendEmail(client asynqClient, message *SendEmail, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	task, err := NewSendEmailTaskWithHeaders(message, nil)
	if err != nil {
		return nil, nil, err
	}

	info, err := client.Enqueue(task, opts...)
	if err != nil {
		return nil, nil, err
	}

	return task, info, nil
}

// EnqueueSendEmailContext pushes a [SendEmail] task to the queue.
//
// Additional [asynq.Option] can be passed to override the options set by [NewSendEmailTask].
//
// This function is auto-generated.
func EnqueueSendEmailContext(ctx context.Context, client asynqClient, message *SendEmail, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	return EnqueueSendEmailContextWithHeaders(ctx, client, message, nil, opts...)
}

// EnqueueSendEmailContextWithHeaders pushes a [SendEmail] task to the queue.
//
// It supports task headers introduced with asynq 0.26.0.
//
// Additional [asynq.Option] can be passed to override the options set by [NewSendEmailTask].
//
// This function is auto-generated.
func EnqueueSendEmailContextWithHeaders(ctx context.Context, client asynqClient, message *SendEmail, headers map[string]string, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	task, err := NewSendEmailTaskWithHeaders(message, headers)
	if err != nil {
		return nil, nil, err
	}

	info, err := client.EnqueueContext(ctx, task, opts...)
	if err != nil {
		return nil, nil, err
	}

	return task, info, nil
}

// EnqueueSendEmailWithHeaders pushes a [SendEmail] task to the queue.
//
// It supports task headers introduced with asynq 0.26.0.
//
// Additional [asynq.Option] can be passed to override the options set by [NewSendEmailTask].
//
// This function is auto-generated.
func EnqueueSendEmailWithHeaders(client asynqClient, message *SendEmail, headers map[string]string, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	task, err := NewSendEmailTaskWithHeaders(message, headers)
	if err != nil {
		return nil, nil, err
	}

	info, err := client.Enqueue(task, opts...)
	if err != nil {
		return nil, nil, err
	}

	return task, info, nil
}

// EnqueueSendSMS pushes a [SendSMS] task to the queue.
//
// Additional [asynq.Option] can be passed to override the options set by [NewSendSMSTask].
//
// This function is auto-generated.
func EnqueueSendSMS(client asynqClient, message *SendSMS, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	task, err := NewSendSMSTaskWithHeaders(message, nil)
	if err != nil {
		return nil, nil, err
	}

	info, err := client.Enqueue(task, opts...)
	if err != nil {
		return nil, nil, err
	}

	return task, info, nil
}

// EnqueueSendSMSContext pushes a [SendSMS] task to the queue.
//
// Additional [asynq.Option] can be passed to override the options set by [NewSendSMSTask].
//
// This function is auto-generated.
func EnqueueSendSMSContext(ctx context.Context, client asynqClient, message *SendSMS, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	return EnqueueSendSMSContextWithHeaders(ctx, client, message, nil, opts...)
}

// EnqueueSendSMSContextWithHeaders pushes a [SendSMS] task to the queue.
//
// It supports task headers introduced with asynq 0.26.0.
//
// Additional [asynq.Option] can be passed to override the options set by [NewSendSMSTask].
//
// This function is auto-generated.
func EnqueueSendSMSContextWithHeaders(ctx context.Context, client asynqClient, message *SendSMS, headers map[string]string, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	task, err := NewSendSMSTaskWithHeaders(message, headers)
	if err != nil {
		return nil, nil, err
	}

	info, err := client.EnqueueContext(ctx, task, opts...)
	if err != nil {
		return nil, nil, err
	}

	return task, info, nil
}

// EnqueueSendSMSWithHeaders pushes a [SendSMS] task to the queue.
//
// It supports task headers introduced with asynq 0.26.0.
//
// Additional [asynq.Option] can be passed to override the options set by [NewSendSMSTask].
//
// This function is auto-generated.
func EnqueueSendSMSWithHeaders(client asynqClient, message *SendSMS, headers map[string]string, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	task, err := NewSendSMSTaskWithHeaders(message, headers)
	if err != nil {
		return nil, nil, err
	}

	info, err := client.Enqueue(task, opts...)
	if err != nil {
		return nil, nil, err
	}

	return task, info, nil
}
