// Code generated by "asynq-codegen"; DO NOT EDIT

package example02

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"time"

	"github.com/hibiken/asynq"
)

// Auto-generated constants for use with [asynq.NewTask], [asynq.ServeMux.Handle],
// and [asynq.ServeMux.HandleFunc].
const (
	// TypeExampleTask is wired to [asynq.Task.Type], [asynq.ServeMux.Handle] and [asynq.ServeMux.HandleFunc].
	TypeExampleTask = "example02:sample_task"
)

type asynqClient interface {
	// EnqueueContext is https://pkg.go.dev/github.com/hibiken/asynq#Client.EnqueueContext.
	EnqueueContext(context.Context, *asynq.Task, ...asynq.Option) (*asynq.TaskInfo, error)
}

type asynqMux interface {
	// HandleFunc is https://pkg.go.dev/github.com/hibiken/asynq#ServeMux.HandleFunc.
	HandleFunc(string, func(context.Context, *asynq.Task) error)
}

// ExampleTaskProcessor describes a function that processes [ExampleTask].
//
// This type is auto-generated.
type ExampleTaskProcessor = func(context.Context, *ExampleTask) error

// Processors defines methods to process messages by their type.
//
// This type is auto-generated.
type Processors struct {
	ExampleTask ExampleTaskProcessor
}

// Handle register all non-nil handlers with [asynq.ServeMux.HandleFunc].
func (p *Processors) Handle(mux asynqMux) {
	if p.ExampleTask != nil {
		mux.HandleFunc(TypeExampleTask, NewExampleTaskProcessor(p.ExampleTask))
	}
}

// HandleAll register all handlers with [asynq.ServeMux.HandleFunc]. It returns an error if any handler is nil.
func (p *Processors) HandleAll(mux asynqMux) error {
	if p.ExampleTask == nil {
		return fmt.Errorf("nil Processors.ExampleTask")
	}

	mux.HandleFunc(TypeExampleTask, NewExampleTaskProcessor(p.ExampleTask))

	return nil
}

// NewExampleTaskFromJSON consumes a JSON input and returns a [ExampleTask].
// Any error returned by [json.Unmarshal] will be returned as-is.
//
// This function is auto-generated.
func NewExampleTaskFromJSON(r io.Reader) (*ExampleTask, error) {
	var out ExampleTask

	if err := json.NewDecoder(r).Decode(&out); err != nil {
		return nil, err
	}

	return &out, nil
}

// NewExampleTaskFromJSONBytes reads a JSON bytestream and returns a [ExampleTask].
//
// Any error returned by [json.Unmarshal] will be returned as-is.
//
// This function is auto-generated.
func NewExampleTaskFromJSONBytes(b []byte) (*ExampleTask, error) {
	var out ExampleTask

	if err := json.Unmarshal(b, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// NewExampleTaskTask takes a [ExampleTask] pointer and returns a new [asynq.Task] with
// its typename set to [TypeExampleTask].
//
// It returns an error if the pointer is nil, or if it cannot be marshalled.
//
// Task's options:
//
//   - Max retries: 1
//   - Timeout: 10s
//
// This function is auto-generated.
func NewExampleTaskTask(t *ExampleTask) (*asynq.Task, error) {
	if t == nil {
		return nil, fmt.Errorf("nil ExampleTask pointer")
	}

	payload, err := json.Marshal(t)
	if err != nil {
		return nil, fmt.Errorf("marshalling ExampleTask: %w", err)
	}

	return asynq.NewTask(
		TypeExampleTask,
		payload,
		asynq.MaxRetry(1),
		asynq.Timeout(10000*time.Millisecond),
	), nil
}

// NewExampleTaskProcessor wraps a [ExampleTaskProcessor] function so that it can be passed
// to [asynq.ServeMux.Handle] and [asynq.ServeMux.HandleFunc].
//
// Notes about the returned function:
//   - it will reject nil tasks and tasks of which the typename does not match [TypeExampleTask].
//   - it will return an error if a task's payload cannot be unmarshalled.
//   - it will return any received error as-is, including [asynq.SkipRetry] and [asynq.RevokeTask].
//
// This function is auto-generated.
func NewExampleTaskProcessor(fn ExampleTaskProcessor) func(context.Context, *asynq.Task) error {
	return func(ctx context.Context, task *asynq.Task) error {
		if task == nil {
			return fmt.Errorf("ExampleTaskProcessor invoked with nil task")
		}

		if task.Type() != TypeExampleTask {
			return fmt.Errorf("ExampleTaskProcessor invoked with task of type %s instead of %s", task.Type(), TypeExampleTask)
		}

		p := task.Payload()

		if len(p) == 0 {
			return fmt.Errorf("ExampleTaskProcessor invoked with void payload")
		}

		var message ExampleTask

		if err := json.Unmarshal(p, &message); err != nil {
			return fmt.Errorf("ExampleTaskProcessor invoked with corrupt payload: %w", err)
		}

		return fn(ctx, &message)
	}
}

// EnqueueExampleTaskContext pushes a [ExampleTask] task to the queue.
//
// Additional [asynq.Option] can be passed to override the options set by [NewExampleTaskTask].
//
// This function is auto-generated.
func EnqueueExampleTaskContext(ctx context.Context, client asynqClient, message *ExampleTask, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	task, err := NewExampleTaskTask(message)
	if err != nil {
		return nil, nil, err
	}

	info, err := client.EnqueueContext(ctx, task, opts...)
	if err != nil {
		return nil, nil, err
	}

	return task, info, nil
}
