// Code generated by "asynq-codegen"; DO NOT EDIT

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"time"

	"github.com/hibiken/asynq"
)

// Auto-generated constants for use with [asynq.NewTask], [asynq.ServeMux.Handle],
// and [asynq.ServeMux.HandleFunc].
const (
	// TypeTask01 is wired to [asynq.Task.Type], [asynq.ServeMux.Handle] and [asynq.ServeMux.HandleFunc].
	TypeTask01 = "main:task_1"
	// TypeTask02 is wired to [asynq.Task.Type], [asynq.ServeMux.Handle] and [asynq.ServeMux.HandleFunc].
	TypeTask02 = "main:task_2"
)

type asynqClient interface {
	// Enqueue is https://pkg.go.dev/github.com/hibiken/asynq#Client.Enqueue.
	Enqueue(*asynq.Task, ...asynq.Option) (*asynq.TaskInfo, error)
	// EnqueueContext is https://pkg.go.dev/github.com/hibiken/asynq#Client.EnqueueContext.
	EnqueueContext(context.Context, *asynq.Task, ...asynq.Option) (*asynq.TaskInfo, error)
}

type asynqMux interface {
	// HandleFunc is https://pkg.go.dev/github.com/hibiken/asynq#ServeMux.HandleFunc.
	HandleFunc(string, func(context.Context, *asynq.Task) error)
}

// Task01Processor describes a function that processes [Task01].
//
// This type is auto-generated.
type Task01Processor = func(context.Context, *Task01, map[string]string) error

// Task02Processor describes a function that processes [Task02].
//
// This type is auto-generated.
type Task02Processor = func(context.Context, *Task02, map[string]string) error

// Processors defines methods to process messages by their type.
//
// This type is auto-generated.
type Processors struct {
	Task01 Task01Processor
	Task02 Task02Processor
}

// Handle register all non-nil handlers with [asynq.ServeMux.HandleFunc].
//
// This function is auto-generated.
func (p *Processors) Handle(mux asynqMux) {
	if p.Task01 != nil {
		mux.HandleFunc(TypeTask01, NewTask01Processor(p.Task01))
	}

	if p.Task02 != nil {
		mux.HandleFunc(TypeTask02, NewTask02Processor(p.Task02))
	}
}

// HandleAll register all handlers with [asynq.ServeMux.HandleFunc]. It returns an error if any handler is nil.
//
// This function is auto-generated.
func (p *Processors) HandleAll(mux asynqMux) error {
	if p.Task01 == nil {
		return fmt.Errorf("nil Processors.Task01")
	}

	if p.Task02 == nil {
		return fmt.Errorf("nil Processors.Task02")
	}

	mux.HandleFunc(TypeTask01, NewTask01Processor(p.Task01))

	mux.HandleFunc(TypeTask02, NewTask02Processor(p.Task02))

	return nil
}

// Run wires up a new [asynq.Server] with an [asynq.ServeMux] instantiated using the provided
// options and middlewares.
//
// This function is auto-generated.
func (p *Processors) Run(redisConnOpt asynq.RedisConnOpt, cfg asynq.Config, middlewares ...asynq.MiddlewareFunc) error {
	mux := asynq.NewServeMux()
	mux.Use(middlewares...)

	if err := p.HandleAll(mux); err != nil {
		return fmt.Errorf("registering mux handler: %w", err)
	}

	return asynq.NewServer(redisConnOpt, cfg).Run(mux)
}

// NewTask01FromJSON consumes a JSON input and returns a [Task01].
// Any error returned by [json.Unmarshal] will be returned as-is.
//
// This function is auto-generated.
func NewTask01FromJSON(r io.Reader) (*Task01, error) {
	var out Task01

	if err := json.NewDecoder(r).Decode(&out); err != nil {
		return nil, err
	}

	return &out, nil
}

// NewTask01FromJSONBytes reads a JSON bytestream and returns a [Task01].
//
// Any error returned by [json.Unmarshal] will be returned as-is.
//
// This function is auto-generated.
func NewTask01FromJSONBytes(b []byte) (*Task01, error) {
	var out Task01

	if err := json.Unmarshal(b, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// NewTask01Task calls [NewTask01TaskWithHeaders] with nil headers.
//
// This function is auto-generated.
func NewTask01Task(t *Task01) (*asynq.Task, error) {
	return NewTask01TaskWithHeaders(t, nil)
}

// NewTask01TaskWithHeaders takes a [Task01] pointer and returns a new [asynq.Task] with
// its typename set to [TypeTask01].
//
// It calls [asynq.NewTaskWithHeaders] introduced with asynq 0.26.0.
//
// It returns an error if the pointer is nil, or if it cannot be marshalled.
//
// Task's options:
//
//   - Max retries: 5
//   - Retention: 24h0m0s
//   - Timeout: 1m0s
//
// This function is auto-generated.
func NewTask01TaskWithHeaders(t *Task01, headers map[string]string) (*asynq.Task, error) {
	if t == nil {
		return nil, fmt.Errorf("nil Task01 pointer")
	}

	payload, err := json.Marshal(t)
	if err != nil {
		return nil, fmt.Errorf("marshalling Task01: %w", err)
	}

	return asynq.NewTaskWithHeaders(
		TypeTask01,
		payload,
		headers,
		asynq.MaxRetry(5),
		asynq.Retention(86400000*time.Millisecond),
		asynq.Timeout(60000*time.Millisecond),
	), nil
}

// NewTask02FromJSON consumes a JSON input and returns a [Task02].
// Any error returned by [json.Unmarshal] will be returned as-is.
//
// This function is auto-generated.
func NewTask02FromJSON(r io.Reader) (*Task02, error) {
	var out Task02

	if err := json.NewDecoder(r).Decode(&out); err != nil {
		return nil, err
	}

	return &out, nil
}

// NewTask02FromJSONBytes reads a JSON bytestream and returns a [Task02].
//
// Any error returned by [json.Unmarshal] will be returned as-is.
//
// This function is auto-generated.
func NewTask02FromJSONBytes(b []byte) (*Task02, error) {
	var out Task02

	if err := json.Unmarshal(b, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// NewTask02Task calls [NewTask02TaskWithHeaders] with nil headers.
//
// This function is auto-generated.
func NewTask02Task(t *Task02) (*asynq.Task, error) {
	return NewTask02TaskWithHeaders(t, nil)
}

// NewTask02TaskWithHeaders takes a [Task02] pointer and returns a new [asynq.Task] with
// its typename set to [TypeTask02].
//
// It calls [asynq.NewTaskWithHeaders] introduced with asynq 0.26.0.
//
// It returns an error if the pointer is nil, or if it cannot be marshalled.
//
// Task's options:
//
//   - Max retries: 5
//   - Retention: 24h0m0s
//   - Timeout: 1m0s
//
// This function is auto-generated.
func NewTask02TaskWithHeaders(t *Task02, headers map[string]string) (*asynq.Task, error) {
	if t == nil {
		return nil, fmt.Errorf("nil Task02 pointer")
	}

	payload, err := json.Marshal(t)
	if err != nil {
		return nil, fmt.Errorf("marshalling Task02: %w", err)
	}

	return asynq.NewTaskWithHeaders(
		TypeTask02,
		payload,
		headers,
		asynq.MaxRetry(5),
		asynq.Retention(86400000*time.Millisecond),
		asynq.Timeout(60000*time.Millisecond),
	), nil
}

// NewTask01Processor wraps a [Task01Processor] function so that it can be passed
// to [asynq.ServeMux.Handle] and [asynq.ServeMux.HandleFunc].
//
// Notes about the returned function:
//     - it will reject nil tasks and tasks of which the typename does not match [TypeTask01].
//     - it will return an error if a task's payload cannot be unmarshalled.
//     - it will return any received error as-is, including [asynq.SkipRetry] and [asynq.RevokeTask].
//
// This function is auto-generated.
func NewTask01Processor(fn Task01Processor) func(context.Context, *asynq.Task) error {
	return func(ctx context.Context, task *asynq.Task) error {
		if task == nil {
			return fmt.Errorf("Task01Processor invoked with nil task")
		}

		if task.Type() != TypeTask01 {
			return fmt.Errorf("Task01Processor invoked with task of type %s instead of %s", task.Type(), TypeTask01)
		}

		p := task.Payload()

		if len(p) == 0 {
			return fmt.Errorf("Task01Processor invoked with void payload")
		}

		var message Task01

		if err := json.Unmarshal(p, &message); err != nil {
			return fmt.Errorf("Task01Processor invoked with corrupt payload: %w", err)
		}

		h := task.Headers()
		if h == nil {
			h = map[string]string{}
		}

		return fn(ctx, &message, h)
	}
}

// NewTask02Processor wraps a [Task02Processor] function so that it can be passed
// to [asynq.ServeMux.Handle] and [asynq.ServeMux.HandleFunc].
//
// Notes about the returned function:
//     - it will reject nil tasks and tasks of which the typename does not match [TypeTask02].
//     - it will return an error if a task's payload cannot be unmarshalled.
//     - it will return any received error as-is, including [asynq.SkipRetry] and [asynq.RevokeTask].
//
// This function is auto-generated.
func NewTask02Processor(fn Task02Processor) func(context.Context, *asynq.Task) error {
	return func(ctx context.Context, task *asynq.Task) error {
		if task == nil {
			return fmt.Errorf("Task02Processor invoked with nil task")
		}

		if task.Type() != TypeTask02 {
			return fmt.Errorf("Task02Processor invoked with task of type %s instead of %s", task.Type(), TypeTask02)
		}

		p := task.Payload()

		if len(p) == 0 {
			return fmt.Errorf("Task02Processor invoked with void payload")
		}

		var message Task02

		if err := json.Unmarshal(p, &message); err != nil {
			return fmt.Errorf("Task02Processor invoked with corrupt payload: %w", err)
		}

		h := task.Headers()
		if h == nil {
			h = map[string]string{}
		}

		return fn(ctx, &message, h)
	}
}

// EnqueueTask01 pushes a [Task01] task to the queue.
//
// Additional [asynq.Option] can be passed to override the options set by [NewTask01Task].
//
// This function is auto-generated.
func EnqueueTask01(client asynqClient, message *Task01, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	task, err := NewTask01TaskWithHeaders(message, nil)
	if err != nil {
		return nil, nil, err
	}

	info, err := client.Enqueue(task, opts...)
	if err != nil {
		return nil, nil, err
	}

	return task, info, nil
}

// EnqueueTask01Context pushes a [Task01] task to the queue.
//
// Additional [asynq.Option] can be passed to override the options set by [NewTask01Task].
//
// This function is auto-generated.
func EnqueueTask01Context(ctx context.Context, client asynqClient, message *Task01, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	return EnqueueTask01ContextWithHeaders(ctx, client, message, nil, opts...)
}

// EnqueueTask01ContextWithHeaders pushes a [Task01] task to the queue.
//
// It supports task headers introduced with asynq 0.26.0.
//
// Additional [asynq.Option] can be passed to override the options set by [NewTask01Task].
//
// This function is auto-generated.
func EnqueueTask01ContextWithHeaders(ctx context.Context, client asynqClient, message *Task01, headers map[string]string, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	task, err := NewTask01TaskWithHeaders(message, headers)
	if err != nil {
		return nil, nil, err
	}

	info, err := client.EnqueueContext(ctx, task, opts...)
	if err != nil {
		return nil, nil, err
	}

	return task, info, nil
}

// EnqueueTask01WithHeaders pushes a [Task01] task to the queue.
//
// It supports task headers introduced with asynq 0.26.0.
//
// Additional [asynq.Option] can be passed to override the options set by [NewTask01Task].
//
// This function is auto-generated.
func EnqueueTask01WithHeaders(client asynqClient, message *Task01, headers map[string]string, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	task, err := NewTask01TaskWithHeaders(message, headers)
	if err != nil {
		return nil, nil, err
	}

	info, err := client.Enqueue(task, opts...)
	if err != nil {
		return nil, nil, err
	}

	return task, info, nil
}

// EnqueueTask02 pushes a [Task02] task to the queue.
//
// Additional [asynq.Option] can be passed to override the options set by [NewTask02Task].
//
// This function is auto-generated.
func EnqueueTask02(client asynqClient, message *Task02, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	task, err := NewTask02TaskWithHeaders(message, nil)
	if err != nil {
		return nil, nil, err
	}

	info, err := client.Enqueue(task, opts...)
	if err != nil {
		return nil, nil, err
	}

	return task, info, nil
}

// EnqueueTask02Context pushes a [Task02] task to the queue.
//
// Additional [asynq.Option] can be passed to override the options set by [NewTask02Task].
//
// This function is auto-generated.
func EnqueueTask02Context(ctx context.Context, client asynqClient, message *Task02, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	return EnqueueTask02ContextWithHeaders(ctx, client, message, nil, opts...)
}

// EnqueueTask02ContextWithHeaders pushes a [Task02] task to the queue.
//
// It supports task headers introduced with asynq 0.26.0.
//
// Additional [asynq.Option] can be passed to override the options set by [NewTask02Task].
//
// This function is auto-generated.
func EnqueueTask02ContextWithHeaders(ctx context.Context, client asynqClient, message *Task02, headers map[string]string, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	task, err := NewTask02TaskWithHeaders(message, headers)
	if err != nil {
		return nil, nil, err
	}

	info, err := client.EnqueueContext(ctx, task, opts...)
	if err != nil {
		return nil, nil, err
	}

	return task, info, nil
}

// EnqueueTask02WithHeaders pushes a [Task02] task to the queue.
//
// It supports task headers introduced with asynq 0.26.0.
//
// Additional [asynq.Option] can be passed to override the options set by [NewTask02Task].
//
// This function is auto-generated.
func EnqueueTask02WithHeaders(client asynqClient, message *Task02, headers map[string]string, opts ...asynq.Option) (*asynq.Task, *asynq.TaskInfo, error) {
	task, err := NewTask02TaskWithHeaders(message, headers)
	if err != nil {
		return nil, nil, err
	}

	info, err := client.Enqueue(task, opts...)
	if err != nil {
		return nil, nil, err
	}

	return task, info, nil
}
